export const INVALIDATE_FORM = "INVALIDATE_FORM";
// authentication
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const CLOSE_AUTH_FORM = "CLOSE_AUTH_FORM";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const REQUEST_AUTHENTICATION = "REQUEST_AUTHENTICATION";
export const REQUEST_SIGN_OUT = "REQUEST_SIGN_OUT";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
export const SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM";
export const SHOW_SIGN_UP_FORM = "SHOW_SIGN_UP_FORM";
// cowsAndBulls
export const CREATE_NEW_COWS_AND_BULLS_GAME = "CREATE_NEW_COWS_AND_BULLS_GAME";
export const SELECT_WINNING_WORD_FOR_COWS_AND_BULLS = "SELECT_WINNING_WORD_FOR_COWS_AND_BULLS";
export const SET_GAME = "SET_GAME";
export const SET_GUESS = "SET_GUESS";
export const SET_COWS_AND_BULLS_ERROR = "SET_COWS_AND_BULLS_ERROR";
export const USER_DID_WIN = "USER_DID_WIN";
export const USER_DID_NOT_WIN = "USER_DID_NOT_WIN";
export const UPDATE_COWS_AND_BULLS_GAME = "UPDATE_COWS_AND_BULLS_GAME";
export const WORD_NOT_IN_GAME = "WORD_NOT_IN_GAME";
// error
// export const SET_ERROR = "SET_ERROR";
// fourLetterWord
export const ADD_FOUR_LETTER_WORD = "ADD_FOUR_LETTER_WORD";
export const DELETE_FOUR_LETTER_WORD = "DELETE_FOUR_LETTER_WORD";
export const LOAD_FOUR_LETTER_WORD = "LOAD_FOUR_LETTER_WORD";
export const LOAD_FOUR_LETTER_WORDS = "LOAD_FOUR_LETTER_WORDS";
export const UPDATE_FOUR_LETTER_WORD = "UPDATE_FOUR_LETTER_WORD";
export const RANDOM_FOUR_LETTER_WORD = "RANDOM_FOUR_LETTER_WORD";
export const REQUEST_FOUR_LETTER_WORD = "REQUEST_FOUR_LETTER_WORD";
export const REQUEST_FOUR_LETTER_WORDS = "REQUEST_FOUR_LETTER_WORDS";
export const SET_FOUR_LETTER_WORD_ERROR = "SET_FOUR_LETTER_WORD_ERROR";
export const SET_FOUR_LETTER_WORD = "SET_FOUR_LETTER_WORD";
export const SET_FOUR_LETTER_WORDS = "SET_FOUR_LETTER_WORDS";
// prefixSuffixRoot
export const ADD_PREFIX_SUFFIX_ROOT = "ADD_PREFIX_SUFFIX_ROOT";
export const DELETE_PREFIX_SUFFIX_ROOT = "DELETE_PREFIX_SUFFIX_ROOT";
export const LOAD_PREFIX_SUFFIX_ROOT = "LOAD_PREFIX_SUFFIX_ROOT";
export const LOAD_PREFIX_SUFFIX_ROOTS = "LOAD_PREFIX_SUFFIX_ROOTS";
export const UPDATE_PREFIX_SUFFIX_ROOT = "UPDATE_PREFIX_SUFFIX_ROOT";
export const RANDOM_PREFIX_SUFFIX_ROOT = "RANDOM_PREFIX_SUFFIX_ROOT";
export const REQUEST_PREFIX_SUFFIX_ROOT = "REQUEST_PREFIX_SUFFIX_ROOT";
export const REQUEST_PREFIX_SUFFIX_ROOTS = "REQUEST_PREFIX_SUFFIX_ROOTS";
export const SET_PREFIX_SUFFIX_ROOT_ERROR = "SET_PREFIX_SUFFIX_ROOT_ERROR";
export const SET_PREFIX_SUFFIX_ROOT = "SET_PREFIX_SUFFIX_ROOT";
export const SET_PREFIX_SUFFIX_ROOTS = "SET_PREFIX_SUFFIX_ROOTS";
// verbo
export const ADD_VERBO = "ADD_VERBO";
export const DELETE_VERBO = "DELETE_VERBO";
export const LOAD_VERBO = "LOAD_VERBO";
export const LOAD_VERBOS = "LOAD_VERBOS";
export const UPDATE_VERBO = "UPDATE_VERBO";
export const RANDOM_VERBO = "RANDOM_VERBO";
export const REQUEST_VERBO = "REQUEST_VERBO";
export const REQUEST_VERBOS = "REQUEST_VERBOS";
export const SET_VERBO = "SET_VERBO";
export const SET_VERBOS = "SET_VERBOS";
export const SET_VERBO_ERROR = "SET_VERBO_ERROR";
export const SHOW_ENGLISH = "SHOW_ENGLISH";
