// authentication
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const CLOSE_AUTH_FORM = "CLOSE_AUTH_FORM";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const REQUEST_AUTHENTICATION = "REQUEST_AUTHENTICATION";
export const REQUEST_SIGN_OUT = "REQUEST_SIGN_OUT";
export const SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM";
export const SHOW_SIGN_UP_FORM = "SHOW_SIGN_UP_FORM";
