export const CREATE_FOUR_LETTER_WORD = 'CREATE_FOUR_LETTER_WORD';
export const DELETE_FOUR_LETTER_WORD = 'DELETE_FOUR_LETTER_WORD';
export const GET_FOUR_LETTER_WORD = 'GET_FOUR_LETTER_WORD';
export const GET_FOUR_LETTER_WORDS = 'GET_FOUR_LETTER_WORDS';
export const GET_RANDOM_FOUR_LETTER_WORD = 'GET_RANDOM_FOUR_LETTER_WORD';
export const UPDATE_FOUR_LETTER_WORD = 'UPDATE_FOUR_LETTER_WORD';

export const CREATE_GAME = 'CREATE_GAME';
export const DELETE_GAME = 'DELETE_GAME';
export const GET_GAME = 'GET_GAME';
export const GET_GAMES = 'GET_GAMES';
export const UPDATE_GAME = 'UPDATE_GAME';

export const CREATE_PREFIX_SUFFIX_ROOT = 'CREATE_PREFIX_SUFFIX_ROOT';
export const DELETE_PREFIX_SUFFIX_ROOT = 'DELETE_PREFIX_SUFFIX_ROOT';
export const GET_PREFIX_SUFFIX_ROOT = 'GET_PREFIX_SUFFIX_ROOT';
export const GET_PREFIX_SUFFIX_ROOTS = 'GET_PREFIX_SUFFIX_ROOTS';
export const GET_RANDOM_PREFIX_SUFFIX_ROOT = 'GET_RANDOM_PREFIX_SUFFIX_ROOT';
export const UPDATE_PREFIX_SUFFIX_ROOT = 'UPDATE_PREFIX_SUFFIX_ROOT';

export const CREATE_USER = 'CREATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const GET_USER = 'GET_USER';
export const GET_USERS = 'GET_USERS';
export const GET_RANDOM_USER = 'GET_RANDOM_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const CREATE_VERBO = 'CREATE_VERBO';
export const DELETE_VERBO = 'DELETE_VERBO';
export const GET_VERBO = 'GET_VERBO';
export const GET_VERBOS = 'GET_VERBOS';
export const GET_RANDOM_VERBO = 'GET_RANDOM_VERBO';
export const UPDATE_VERBO = 'UPDATE_VERBO';
